project:
  type: book

book:
  title: "Tensor Tonic"
  author: "Norah Jones"
  date: "2025-10-30"
  chapters:
  - index.md
  - part: Activation Functions
    chapters:
      - activation-functions/implement-sigmoid-in-numpy.md
    

format:
  html:
    theme:
      dark: darkly
      light: flatly
  pdf:
    documentclass: scrreprt



